title:            title
#logo:
search:			  false
#Change url to your domain. Leave localhost:4000 server or blank when working locally.

disclaimer: Scout should have a disclaimer about the content of the landing page

# Owner/author information
owner:
  name:           Scout SEO
  avatar:         logo.png
  email:          example@example.com
  description:    Description of Scout and a logo near it
  twitter:        twitter-account
  facebook:       facebook-link
  github:
  stackexchange:
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  hmfaysalsocial:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
bing_verify:
mixpanel:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Inside page
    url: /inside-page.html


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown
paginate:    4
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
